### ISSUE TITLE
Crazy label file

### ISSUE THREAD

**Issue by FlaviaMS** [kjthoward/OMDC_Stock#19]
There is an issue with the label file to download from the database.
It is generating labels for everything on the databse. Including things that have labels already.
Is this something can can be fixes next week or so?

**Comment by FlaviaMS** [comment]
I know you are super busy..Don't worry about it today at all. And yes you are correct it was fine on the testing one. Let me know if you think I might have broken something, so I won't do it again.

**Comment by kjthoward** [comment]
Was entirely my fault... It Worked correctly when you were using .csv files for the labels, but when you asked to change it .xlsx files I changed the file type it made but forgot to add in the bit that sets each item as being "printed"... Should now be fixed

**Comment by FlaviaMS** [comment]
Please re-open the issue. I was trining Daisy and the problem is still there. Sorry

**Comment by kjthoward** [comment]
The issue is not still there. Everything would still be downloadable once, as things only get marked as "printed" once you've downloaded the file, so the fixed version of the label downloading section would need to be run one time to mark everything as "printed" which is why things were still showing up once.

Just tried and I got this:

![image](https://user-images.githubusercontent.com/40895027/88409320-b3b18700-cdcc-11ea-8287-720680d9a727.png)
